objects/configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ISBOY__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ISBOY</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISGirl__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ISGirl</label>
        <type>Checkbox</type>
    </fields>
    <label>configuration</label>
</CustomObject>

classes/AdminPanelController.cls
public class AdminPanelController {
    
    @AuraEnabled
    public static List<AdminPanelWrapper> getRecords()
    {
         List<AdminPanelWrapper> configwrap = new List<AdminPanelWrapper>();
         List<configuration__c> config  = [Select ISBOY__c,ISGirl__c from configuration__c ];
        
        if(config!= null && config.size() > 0){
             for(configuration__c c :config)
             {
                AdminPanelWrapper configrec  = new AdminPanelWrapper();
                configrec.ISBOY = c.ISBOY__c;
                configrec.ISGirl = c.ISGirl__c;
                configwrap.add(configrec);
    		 }
    
            
		}
         return configwrap;
        
    }
}