objects/Consultant__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Preferred_Location__c</fullName>
        <label>Preferred Location</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Skill__c</fullName>
        <label>Primary Skill</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relevant_Experience__c</fullName>
        <label>Relevant Experience</label>
        <precision>3</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Experience__c</fullName>
        <label>Total Experience</label>
        <precision>3</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Consultant</label>
    <nameField>
        <label>Consultant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/consultantController.cls
public class consultantController {
    
      @AuraEnabled
    public static List < Consultant__c > fetchConsultants() {
        
        return [ SELECT Id, 
                		Name,
                		Phone__c,
                		Preferred_Location__c,
                		Primary_Skill__c,
                		Relevant_Experience__c,
                        Total_Experience__c
                        FROM Consultant__c LIMIT 10 ];
        
        
    }
    


}