objects/Employee2__c.object
<CustomObject>
    <fields>
        <fullName>AGE__c</fullName>
        <label>AGE</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Experienced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Experienced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/showEmployeeRecords.cls
public class showEmployeeRecords {
    @AuraEnabled
    public static List<Employee2__c> showEmployeeRecords()
    {
        List<Employee2__c> employeeList = [Select AGE__c,Experienced__c,FirstName__c,LastName__c from Employee2__c];
        return employeeList;
        
    }
    @AuraEnabled
    public static Employee2__c showRecentEmployeeRecords(Integer age,Boolean IsExperienced,String LastName,String FirstName)
    {
        Employee2__c employee = new Employee2__c(AGE__c=age,Experienced__c=IsExperienced,LastName__c =LastName,FirstName__c=FirstName);
        insert employee;
        return employee;
        
    }
    
    @AuraEnabled
    public static Employee2__c editTheRecord(Id employeeId)
    {
        Employee2__c employee = [Select AGE__c,Experienced__c,FirstName__c,LastName__c from Employee2__c where Id =: employeeId];
        return employee;
    }
    

}