objects/List_of_Students__c.object
<CustomObject>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>FirstName</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>List of Students</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>List of Students Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List of Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RecordController.cls
public class RecordController {
    @AuraEnabled
 
    public static List<List_of_Students__c> getRecords()
    {
        return [Select id,Name__c,Middle_Name__c,LastName__c 
                from List_of_Students__c];
    }
     
    // @AuraEnabled
   // public static List_of_Students__c setRecords(List_of_Students__c listRec)
    //{
      //  upsert listRec;
       // return listRec;
    //} 
 

    
}