objects/Utterance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Utterance Log</relationshipLabel>
        <relationshipName>Utterance_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Utterance__c</fullName>
        <label>Current Utterance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utterance_Log__c</fullName>
        <label>Utterance Log</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Utterance Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utterance Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CookbookBot_HandleIntentDetectFailure.cls
public class CookbookBot_HandleIntentDetectFailure {
    
    public class HandleInput
    {
        @InvocableVariable(required=false)
        public String sCurrentUtterance;
        
        @InvocableVariable(required=false)
        public String sLiveChatTranscriptId;
    }
    
    public class HandleOutput
    {
        @InvocableVariable(required = true)
        public String sTransferMessage;
        
        @InvocableVariable(required = true )
        public Boolean bTransferRequired;
    }
    
    @InvocableMethod(label ='Handle Intent Detection Failure')
    public static list<HandleOutput> handleIntentDetectionFailure(List<HandleInput> inputParameters)
    {
      String sCurrentUtterance = inputParameters[0].sCurrentUtterance;
      String sLiveChatTranscriptId = inputParameters[0].sLiveChatTranscriptId;
        
      List<HandleOutput> outputParameters = new List<HandleOutput>();
      HandleOutput outputParameter = new HandleOutput();
      outputParameter.bTransferRequired = false;
      outputParameter.sTransferMessage = '';
      
     List<Utterance_Log__c> undetectedUtterances = [Select Current_Utterance__c,createdDate from utterance_log__c 
                                                    where Chat_Transcript__c =:sLiveChatTranscriptId
                                                    Order by CreatedDate Desc];
      
       if(undetectedUtterances.size()>=2)
       {
           if(undetectedUtterances.size() > 5)
           {
               outputParameter.bTransferRequired = true;
               outputParameter.sTransferMessage ='Let me find one of our specialists to help you';
		   }
           
           else
           {
               Utterance_Log__c thisUtterance = undetectedUtterances[0];
               Utterance_Log__c lastUtterance = undetectedUtterances[1];
           
           if(thisUtterance.CreatedDate < lastUtterance.CreatedDate.addSeconds(20))
           {
               outputParameter.btransferRequired = true;
               outputParameter.sTransferMessage = 'Im having troubles understanding what you need.Let me find a specialist';
           }
            
               

       }
      
    }
    
       outputParameters.add(outputParameter);      
       return outputParameters;

    }
      
        
        
    
  

}